php:
  preset: laravel
  disabled:
    - unused_use
  finder:
    not-name:
      - index.php
      - server.php

# multiple languages require paid plan :(
#js:
#  finder:
#    not-name:
#      - webpack.mix.js
#css: true
